DeveloperAcademy-POSTECH/MC3_Team10_TalTal

- TalTal/TalTal/Controllers/ReflectionViewController.swift
- TalTal/TalTal/StoryBoard/Reflection.storyboard
> [2022.07.27] Reflection View 구성

- TalTal/TalTal.xcodeproj/project.pbxproj
- TalTal/TalTal/Assets.xcassets/TalTalColor/PointLightPink.colorset/Contents.json
- TalTal/TalTal/Controllers/HistoryViewController.swift
- TalTal/TalTal/Models/MissionDataManager.swift
- TalTal/TalTal/Models/MissionModel.swift
- TalTal/TalTal/StoryBoard/History.storyboard
- TalTal/TalTal/Views/HistoryCell.swift
히스토리 뷰 -> 테이블 뷰 생성
1. 히스토리 뷰 디자인
2. PointLitePink 색상 추가
3. Mission 관련 임시 모델 생성
4. 히스토리 테이블 뷰 생성
5. 히스토리 뷰 컨트롤러 생성
히스토리 테이블 뷰 작업 완료
> [2022.07.27] 히스토리 테이블 뷰

- TalTal/TalTal.xcodeproj/project.pbxproj
- TalTal/TalTal/ AppDelegate.swift
- TalTal/TalTal/Controllers/HistoryViewController.swift
- TalTal/TalTal/Models/CoreData/CompleteMission+CoreDataClass.swift
- TalTal/TalTal/Models/CoreData/CompleteMission+CoreDataProperties.swift
- TalTal/TalTal/Models/MissionDAO.swift
- TalTal/TalTal/TalTal.xcdatamodeld/TalTal.xcdatamodel/contents
코어 데이터 생성 및 적용에 필요한 로직 구현
1. 코어 데이터 생성
2. 코어 데이터 모델 생성
3. 히스토리 뷰 / 코어 데이터 연결
4. 코어 데이터 DAO 생성
- DB연결 전 더미 데이터 삭제
> [2022.07.29] 코어데이터 적용

- TalTal/TalTal/Controllers/HistoryViewController.swift
- TalTal/TalTal/Models/CoreData/CompleteMission+CoreDataProperties.swift
- TalTal/TalTal/Models/MissionDAO.swift
- TalTal/TalTal/Models/MissionModel.swift
- TalTal/TalTal/TalTal.xcdatamodeld/TalTal.xcdatamodel/contents
코어 데이터 관련 코드 정리
1. CompleteMission 엔티티에 stage 어트리뷰트 추가
2. Status enum 타입 Int64 -> String 로 변경
3. READ 메서드 get... -> fetch... 로 변경
코어데이터 엔티티에 어트리뷰트가 추가되어서 
프로젝트 파일에서 컨플릭트 날 수 있어요
확인 부탁드립니다
> [2022.07.29] 코어 데이터 관련 코드 업데이트

- TalTal/TalTal.xcodeproj/project.pbxproj
- TalTal/TalTal/StoryBoard/Base.lproj/Tabbar.storyboard
- TalTal/TalTal/StoryBoard/Reflection.storyboard
Reflection View를 탭바에서 삭제 하였습니다.
테이블뷰 셀을 클릭시 이동하도록 작업하시면 됩니다.
작업사항은 개요와 같습니다.
> [2022.07.29] Reflection.storyboard 수정완료

- TalTal/TalTal/Controllers/HistoryViewController.swift
- TalTal/TalTal/Controllers/ReflectionViewController.swift
- TalTal/TalTal/StoryBoard/History.storyboard
- TalTal/TalTal/TalTal.xcdatamodeld/TalTal.xcdatamodel/contents
HistoryView와 ReflectionView 연결
1. HistoryView와 ReflectionView 연결했습니다.
2. CoreData의 Attribute 중 stage의 이름을 stageValue로 수정하였습니다.
HistoryView의 prepare 메소드(113번째 줄)에서
일간 미션과 주간 미션을 구분하여 미션을 fetch 해야 올바르게 segue가 작동하여 코드를 약간 변경했으니 한번 확인 부탁드립니다.
<table>
<tr>
<td><img src ="https://user-images.githubusercontent.com/103024858/181878485-99b33026-c648-448a-add1-5fdb463dd3b5.png" width = 300 /></td><td><img src ="https://user-images.githubusercontent.com/103024858/181878579-a663ad4b-10bd-4950-8bf8-03b5051008fc.png" width = 300 /></td>
</tr>
</table>
> [2022.07.30] HistoryView와 ReflectionView 연결

- TalTal/TalTal.xcodeproj/project.pbxproj
- TalTal/TalTal/Controllers/Mission/MissionQuestView.swift
- TalTal/TalTal/Controllers/Mission/MissionViewController.swift
- TalTal/TalTal/StoryBoard/Base.lproj/Tabbar.storyboard
- TalTal/TalTal/StoryBoard/Mission/MissionQuestView.xib
- TalTal/TalTal/StoryBoard/MissionClear.storyboard
미션뷰 버튼을 클릭시 클리어뷰가 나옵니다.
델리게이트 패턴을 추가해서 미션뷰에서 위클리뷰 버튼인지 델리이뷰 버튼인지 구분이 가능해 집니다.
대공사 전에 기조 작업 정도 완성된 모습이고,  혹시 몰라서 남깁니다.
개요와 같습니다.
[내용 기입]
> [2022.07.30] 미션뷰에서 버튼 클릭시 클리어뷰 show되도록 수정

- TalTal/TalTal/Controllers/HistoryViewController.swift
- TalTal/TalTal/Controllers/Mission/MissionQuestView.swift
- TalTal/TalTal/Controllers/Mission/MissionViewController.swift
- TalTal/TalTal/Controllers/MissionClearViewController.swift
- TalTal/TalTal/Models/CoreData/CompleteMission+CoreDataProperties.swift
- TalTal/TalTal/Models/MissionDAO.swift
- TalTal/TalTal/StoryBoard/MissionClear.storyboard
각각의 View들 연결 작업
1. 미션 클리어 뷰에서 확인 버튼 클릭시 기존 버튼 비활성화
2. 활성화 코드도 생성 완료(아직 사용은 안하고 있습니다.)
3. 각각의 뷰와 연결 되면서 변경되어야 하는 것들 변경 
[내용 기입]
> [2022.07.30] 각각의 View 연결 작업

- TalTal/TalTal/Controllers/Mission/MissionViewController.swift
오류 수정및 코드 추가
1. 오류를 수정했습니다
- 버튼 활성화도 비활성화 로직으로 만들어 놨었네요...
3. veiwdidload에 미션을 해결 했다면 비활성화가 되도록 로직 추가했습니다.
-틀만 만들어 놓았고 준아가 검색 하시면 설명이 나올 것입니다.
[내용 기입]
> [2022.07.30] MissionVeiw 버튼 활성화 비활성화 로직추가

- TalTal/TalTal/Controllers/Mission/MissionViewController.swift
UserDefaults 수정
1. UserDefaults에 들어가는 기본 세팅과 로직을 수정하였습니다
2. UserDefaults 세팅에 필요한 메소드들을 추가하였습니다
코드가 상당히 보기 힘들기 때문에 지속적인 리팩토링을 해야 할 것 같습니다
> [2022.07.31] UserDefaults 수정

- TalTal/TalTal/Models/MissionDataManager.swift
- TalTal/TalTal/Models/MissionModel.swift
데이터 로직 수정 및 코어데이터 저장
1.  데이터 로직 수정 및 완료2. 
2. 코어데이터 저장 (MissionDataManage -> saveMission)
> [2022.07.31] 데이터 로직 수정 및 코어데이터 저장

- TalTal/TalTal/Models/MissionDataManager.swift
MissionDataManager 주석 추가
MissionDataManager 주석 추가
> [2022.07.31] MissionDataManager 주석 추가

- TalTal/TalTal/Models/MissionDataManager.swift
[내용 기입]
오류 수정 함수명이 SaveFlection으로 되어있는걸 -> fetchReflection으로 변경해야 동작합니다.
수정완료
1. 작업사항1
2. 작업사항2
[내용 기입]
> [2022.08.01] 오류 수정 함수명이 SaveFlection으로 되어있는걸 -> fetchReflection으로 변경해야 동작합니다.

- TalTal/TalTal/Controllers/Mission/MissionViewController.swift
- TalTal/TalTal/Controllers/MissionClearViewController.swift
- TalTal/TalTal/Models/MissionDAO.swift
- TalTal/TalTal/Models/MissionDataManager.swift
미션 클리어 후에 코어 데이터 저장
미션 클리어 후에 코어 데이터 저장
> [2022.07.31] 미션 클리어 후에 코어 데이터 저장

- TalTal/TalTal/Controllers/HistoryViewController.swift
> [2022.08.01] 히스토리뷰 버그 수정

- TalTal/TalTal/Controllers/Mission/MissionViewController.swift
[내용 기입]
1. 작업사항1
2. 작업사항2
[내용 기입]
> [2022.08.01]일간미션 클리어

- TalTal/TalTal/Models/MissionDataManager.swift
주간 퀘스트 리프레쉬 문제
MissionDataManager > requestWeeklyMission > 
`missions.randomElement() -> filterMissions.randomElement()`
> [2022.08.01] 주간 퀘스트 리프레쉬 문제

- TalTal/TalTal.xcodeproj/project.pbxproj
앱 버전 정보를 1.0에서 1.0.0 으로 수정했습니다.
> [2022.08.02] 앱 버전 정보 수정

- TalTal/TalTal.xcodeproj/project.pbxproj
[Fix] 심사 제출을 위해 빌드버전을 1.0.0(1) -> 1.0.1(2)로 수정하였습니다.
1. 심사 제출을 위해 빌드버전을 1.0.0(1) -> 1.0.1(2)로 수정하였습니다.
- 테스트플라이트에 이미 1.0.1(1) 버전이 있어서 1.0.1(2)로 수정하였습니다.
> [2022.08.03] 심사 제출을 위해 빌드버전을 1.0.0(1) -> 1.0.1(2)로 수정하였습니다.

- TalTal/TalTal.xcodeproj/project.pbxproj
- TalTal/TalTal/Controllers/EndingViewController.swift
- TalTal/TalTal/Controllers/Mission/MissionViewController.swift
- TalTal/TalTal/StoryBoard/Ending.storyboard
- TalTal/TalTal/StoryBoard/Mission/Mission.storyboard
엔딩뷰 작업을 위한 작업을 했습니다.
1. 엔딩뷰를 호출한 뷰를 추가
2. 엔딩뷰 기초공사완료
로컬라이징은 지금 생각나서 추가로 작업해서 올리겠습니다.
> [2022.08.12] EndingVeiw추가를 위한 기초작업

- TalTal/TalTal/Controllers/HistoryViewController.swift
- TalTal/TalTal/Controllers/Mission/MissionViewController.swift
- TalTal/TalTal/Controllers/TabbarViewController.swift
- TalTal/TalTal/StoryBoard/History.storyboard
- TalTal/TalTal/StoryBoard/Mission/Mission.storyboard
- TalTal/en.lproj/Localizable.strings
- TalTal/ko.lproj/Localizable.strings
탭바 아이템의 타이틀을 로컬라이징했습니다.
1. 탭바를 사용하게 된다면, 그리고 로컬라이징을 해야 한다면 앞으로 한번쯤은 겪을 문제가 있으니 꼭 내용을 읽어보시는걸 추천합니다.
TabBarItem.title 로컬라이징
> [Fix] TabBarItem 로컬라이징

- TalTal/TalTal/Controllers/EndingViewController.swift
- TalTal/TalTal/StoryBoard/Ending.storyboard
엔딩뷰 화면을 구성했습니다.
1. 엔딩뷰 화면 구성
2. 일일미션, 주간미션 색상 변경
3. 코어데이터에서 미션 완료 갯수를 가져옴
> [2022.08.23] 엔딩뷰 구현
